### ISSUE TITLE
Nice! LICENSE file?

### ISSUE THREAD

**Issue by hughperkins** [kodemore/chili#11]
Hey, this is great!

I see there is an MIT license batch. Don't suppose... could you add also an MIT `LICENSE` file, so that it is really obviously mit, and so that it shows as MIT in the right hand side of the github repo front page?

**Comment by dkraczkowski** [comment]
Sure.

**Comment by dkraczkowski** [comment]
Done. Version 2.0 is coming. Check it out :) It has much nicer interface and improved performance.

**Comment by hughperkins** [comment]
Thanks!

As far as new interfacr, Ok. My code already uses the existing interface, and does what I need. There is no benefit to me from changing it.

**Comment by hughperkins** [comment]
Honestly, I really liked the v1. The v2 is like a completely different project.

**Comment by hughperkins** [comment]
Oh, ok, dont need to annotate dataclasses. I feel like the documentation could make that clearer. I nearly walked away because having to anntoate my classes seemed like something that would couple me tightly to chili.

**Comment by hughperkins** [comment]
But still, having to create speicalized encoder objects each time seems like a lot more work than the v1 interface.

**Comment by hughperkins** [comment]
```
The chili.encode function takes an object and an optional type hint and returns a dictionary.

The chili.decode function takes a dictionary, a type hint, and returns an object.
```

This should go at the start of your doc I feel...
