### ISSUE TITLE
Encoder.encode does not work like encode() when using custom types. Bug or intended?

### ISSUE THREAD

**Issue by Fairlight8** [kodemore/chili#13]
Hello!

I found that the encoding behavior when using custom type encoders and decoders is different between `Encoder[Class].encode(obj)` and `encode(obj, Class, ...)`. Here's the steps to reproduce it:

## Steps to reproduce it

```
from chili import Encoder, TypeEncoder, encode, encodable
from typing import Any

class ExoticClass:
    name: str
    size: int

    def __init__(self, name, size):
        self.name = name
        self.size = size


class ExoticEncoder(TypeEncoder):
    def encode(self, value: ExoticClass):
        return {"name": f"DECODED:{value.name}", "size": -value.size}


type_encoders = {ExoticClass: ExoticEncoder()}

exotic_object = ExoticClass("foo", 5)

print(encode(exotic_object, ExoticClass, type_encoders))
print(Encoder[ExoticClass](encoders=type_encoders).encode(exotic_object))
```

The output of the first print is: `{'name': 'DECODED:foo', 'size': -5}`, as expected.
But the output of the second line is the exception `chili.error.EncoderError@invalid_type: invalid_type`

I think this is because I haven't decorated my class. If I add the decorator like:
```
@encodable
class ExoticClass:
    ...
```

Then, the outputs are `{'name': 'DECODED:foo', 'size': -5}` and `{'name': 'foo', 'size': 5}`.

The conclusion is that the second line always ignores the custom type encoders.

**Comment by dkraczkowski** [comment]
@Fairlight8 Hello, thanks for raising the issue.

You should not need to add `@encodable` decorator for custom types. I will have a look and see where is the problem after my work.

**Comment by Fairlight8** [comment]
Oh, okay, I think I understand. So, the preferred workflow is to register custom type decoders / encoders only for unserializable attributes inside the class, right? Well, to be honest, it makes much more sense.

Okay, thank you. So, should I close the issue?

**Comment by dkraczkowski** [comment]
@Fairlight8 THat's correct ;)

 I will close it ;)
