### ISSUE TITLE
dataclass vs decorated class instantiation differences

### ISSUE THREAD

**Issue by DragosDumitrache** [kodemore/chili#17]
Hello,

I stumbled across the following unexpected behaviour today, wanted to raise it for visibility first.

Let's say I have the following dataclass:

```python
@dataclasses.dataclass
class Contract:
    name: str
    start: int
    duration: int
    price: int
```

If I try instantiating this using an incomplete input, `chili` will do it just fine, it just won't have the `duration` field on it.

```python
invalid_contract = {
    'name': 'Contract 1',
    'start': '0',
    'price': 10
}
contract = decode(invalid_contract, Contract)
```

If I change the class definition to provide a constructor, and I use the same initialisation as above, `chili` will raise an `DecoderError.invalid_type` exception, which is what I was expecting.

```python
@chili.encodable
class Contract:
    name: str
    start: int
    duration: int
    price: int

    def __init__(self, name: str, start: int, duration: int, price:int):
        self.name = name
        self.start = start
        self.duration = duration
        self.price = price
```

I seem to recall `chili` handling this consistently with v1, but I could be wrong, so I wanted to ask for some clarification as to what the desired behaviour is.

**Comment by dkraczkowski** [comment]
@DragosDumitrache  Hi, thanks for raising this. You should use the `@decodable` decorator instead. The `@encodable` allows you to encode it into either JSON or a dict representation. 

You can also use `@serialisable` which stands for both `@encodable` and `@decodable`. 
If a field is missing chilli should be still able to decode your class.
