### ISSUE TITLE
[BUG / IMPROVEMENT] Child class does not receive new schema if parent is already decodable/encodable/serializable

### ISSUE THREAD

**Issue by Fairlight8** [kodemore/chili#25]
Hello again!

I am using chili in an university project I am currently coding, and I just discovered a problem. We have two classes, parent and child. Both of them are serializable. The base class is a basic session, with basic functionality, and the other one inherits the base class, with extra tools.

At some point I realized that chili was not encoding/decoding the objects of the child class properly. And, after some research, I realized that the schema was identical in both classes, parent and child.

Which is the source of the issue, then? When marking classes as encodable / decodable / serializable, the decorator checks this:

```
def _decorate(cls) -> Type[C]:
        if not hasattr(cls, _PROPERTIES):
            setattr(cls, _PROPERTIES, create_schema(cls))
```

What is happening when both classes are marked with the encodable / decodable / serializable decorator? The child class inherits the schema, and the decorator does not update the schema.

I have done some tests, and removing the line `if not hasattr(cls, _PROPERTIES):` solves the issue. I don't know if it breaks anything else. If you agree, I will create a pull request with this solution.

Thanks in advance.

**Comment by dkraczkowski** [comment]
Hello @Fairlight8, 
It is a bit against what I wanted to achieve. Some of the classes should not be serialisable if they are not explicitly defined as such. I understand the problem, but that would need a bit complex solution which I am looking at currently.

**Comment by Fairlight8** [comment]
Hello, @dkraczkowski, and thanks for your answer.

But I think we are not talking about the same issue. What I mean is:

Two classes: A and B, where A is the parent class and B inherits A. Both of them are serializable, and **I mark them as serializable explicitly**. And the problem comes when both classes use the same schema. Why? Because the decorator does not work if the class is already serializable. If a child class is marked with the serializable decorator, it will do nothing because it already inherited a schema from the parent class, and the schema will not be overwritten.

**Comment by dkraczkowski** [comment]
@Fairlight8  oic... That's a bug. Can you share a snippet with your use case so I can use it to write a test?

**Comment by Fairlight8** [comment]
@dkraczkowski 

```
from chili import serializable, encode

@serializable
class Parent:
    foo : int

    def __init__(self, foo):
        self.foo = foo

    def some_logic(self):
        pass

@serializable
class Child(Parent):
    bar: float

    def __init__(self, foo, bar):
        super().__init__(foo)
        self.bar = bar

    def more_logic(self):
        pass

parent_obj = Parent(5)
child_obj = Child(7, 0.2)

encoded_parent = encode(parent_obj)
print(encoded_parent) #This should be {foo: 5}, and it will be correct.

encoded_child = encode(child_obj)
print(encoded_child) #This should be {foo: 7, bar: 0.2}, but it will be {foo: 7} instead, because it uses the schema of the Parent class.
```

I localized the error, so if you want, I can write a pull request with the solution.

**Comment by dkraczkowski** [comment]
@Fairlight8 Sure, I would appreciate that!

**Comment by Fairlight8** [comment]
Created a pull request, @dkraczkowski . It has some issues, please read it. If it is not feasible, I have an alternative solution.

**Comment by dkraczkowski** [comment]
@Fairlight8 Thanks for your patience, released fixes and a couple of improvements. Please check: https://github.com/kodemore/chili/releases/tag/2.6.0

**Comment by Fairlight8** [comment]
@dkraczkowski thanks to you, for your work. I am sorry that my PR wasn't helpful, but it was definitely a naive approach. Thanks again!
